// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfzjrmypwqqgncqkytds.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmempybXlwd3FxZ25jcWt5dGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4MjYzOTUsImV4cCI6MjA3NDQwMjM5NX0.07utRxhZdXpie3uyzJrimyWtnm0694-BPFJv4xaZ6NU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});